#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : mailcommon
Version  : 18.08.0
Release  : 2
URL      : https://download.kde.org/stable/applications/18.08.0/src/mailcommon-18.08.0.tar.xz
Source0  : https://download.kde.org/stable/applications/18.08.0/src/mailcommon-18.08.0.tar.xz
Source99 : https://download.kde.org/stable/applications/18.08.0/src/mailcommon-18.08.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: mailcommon-lib
Requires: mailcommon-license
Requires: mailcommon-locales
BuildRequires : akonadi-contacts-dev
BuildRequires : akonadi-dev
BuildRequires : akonadi-mime-dev
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : gpgme-dev
BuildRequires : gpgme-extras
BuildRequires : kcontacts-dev
BuildRequires : kidentitymanagement-dev
BuildRequires : kimap-dev
BuildRequires : kmailtransport-dev
BuildRequires : kmime-dev
BuildRequires : kpimtextedit-dev
BuildRequires : libassuan-dev
BuildRequires : libgpg-error-dev
BuildRequires : libkdepim-dev
BuildRequires : libkleo-dev
BuildRequires : mailimporter-dev
BuildRequires : messagelib-dev
BuildRequires : phonon-dev
BuildRequires : pimcommon-dev
BuildRequires : qtbase-dev qtbase-extras mesa-dev
BuildRequires : syntax-highlighting-dev

%description
No detailed description available

%package dev
Summary: dev components for the mailcommon package.
Group: Development
Requires: mailcommon-lib
Provides: mailcommon-devel

%description dev
dev components for the mailcommon package.


%package lib
Summary: lib components for the mailcommon package.
Group: Libraries
Requires: mailcommon-license

%description lib
lib components for the mailcommon package.


%package license
Summary: license components for the mailcommon package.
Group: Default

%description license
license components for the mailcommon package.


%package locales
Summary: locales components for the mailcommon package.
Group: Default

%description locales
locales components for the mailcommon package.


%prep
%setup -q -n mailcommon-18.08.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535305640
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1535305640
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/mailcommon
cp COPYING %{buildroot}/usr/share/doc/mailcommon/COPYING
cp COPYING.LIB %{buildroot}/usr/share/doc/mailcommon/COPYING.LIB
pushd clr-build
%make_install
popd
%find_lang libmailcommon

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/MailCommon/AccountConfigOrderDialog
/usr/include/KF5/MailCommon/AddTagDialog
/usr/include/KF5/MailCommon/BackupJob
/usr/include/KF5/MailCommon/CollectionExpiryPage
/usr/include/KF5/MailCommon/CollectionGeneralPage
/usr/include/KF5/MailCommon/CryptoUtils
/usr/include/KF5/MailCommon/DBusOperators
/usr/include/KF5/MailCommon/ExpireCollectionAttribute
/usr/include/KF5/MailCommon/FavoriteCollectionOrderProxyModel
/usr/include/KF5/MailCommon/FavoriteCollectionWidget
/usr/include/KF5/MailCommon/FilterAction
/usr/include/KF5/MailCommon/FilterActionDict
/usr/include/KF5/MailCommon/FilterImporterAbstract
/usr/include/KF5/MailCommon/FilterImporterBalsa
/usr/include/KF5/MailCommon/FilterImporterClawsMail
/usr/include/KF5/MailCommon/FilterImporterExporter
/usr/include/KF5/MailCommon/FilterImporterPathCache
/usr/include/KF5/MailCommon/FilterLog
/usr/include/KF5/MailCommon/FilterManager
/usr/include/KF5/MailCommon/FolderCollectionMonitor
/usr/include/KF5/MailCommon/FolderJob
/usr/include/KF5/MailCommon/FolderRequester
/usr/include/KF5/MailCommon/FolderSelectionDialog
/usr/include/KF5/MailCommon/FolderSettings
/usr/include/KF5/MailCommon/FolderTreeView
/usr/include/KF5/MailCommon/FolderTreeWidget
/usr/include/KF5/MailCommon/FolderTreeWidgetProxyModel
/usr/include/KF5/MailCommon/ItemContext
/usr/include/KF5/MailCommon/JobScheduler
/usr/include/KF5/MailCommon/KMFilterDialog
/usr/include/KF5/MailCommon/MDNStateAttribute
/usr/include/KF5/MailCommon/MailFilter
/usr/include/KF5/MailCommon/MailInterfaces
/usr/include/KF5/MailCommon/MailKernel
/usr/include/KF5/MailCommon/MailUtil
/usr/include/KF5/MailCommon/MetaType
/usr/include/KF5/MailCommon/RedirectDialog
/usr/include/KF5/MailCommon/ResourceReadConfigFile
/usr/include/KF5/MailCommon/SearchPattern
/usr/include/KF5/MailCommon/SearchPatternEdit
/usr/include/KF5/MailCommon/SearchRule
/usr/include/KF5/MailCommon/SearchRuleStatus
/usr/include/KF5/MailCommon/SendMdnHandler
/usr/include/KF5/MailCommon/SnippetsManager
/usr/include/KF5/MailCommon/Tag
/usr/include/KF5/MailCommon/TagWidget
/usr/include/KF5/mailcommon/accountconfigorderdialog.h
/usr/include/KF5/mailcommon/addtagdialog.h
/usr/include/KF5/mailcommon/backupjob.h
/usr/include/KF5/mailcommon/collectionexpirypage.h
/usr/include/KF5/mailcommon/collectiongeneralpage.h
/usr/include/KF5/mailcommon/cryptoutils.h
/usr/include/KF5/mailcommon/dbusoperators.h
/usr/include/KF5/mailcommon/expirecollectionattribute.h
/usr/include/KF5/mailcommon/favoritecollectionorderproxymodel.h
/usr/include/KF5/mailcommon/favoritecollectionwidget.h
/usr/include/KF5/mailcommon/filteraction.h
/usr/include/KF5/mailcommon/filteractiondict.h
/usr/include/KF5/mailcommon/filterimporterabstract.h
/usr/include/KF5/mailcommon/filterimporterbalsa.h
/usr/include/KF5/mailcommon/filterimporterclawsmail.h
/usr/include/KF5/mailcommon/filterimporterexporter.h
/usr/include/KF5/mailcommon/filterimporterpathcache.h
/usr/include/KF5/mailcommon/filterlog.h
/usr/include/KF5/mailcommon/filtermanager.h
/usr/include/KF5/mailcommon/foldercollectionmonitor.h
/usr/include/KF5/mailcommon/folderjob.h
/usr/include/KF5/mailcommon/folderrequester.h
/usr/include/KF5/mailcommon/folderselectiondialog.h
/usr/include/KF5/mailcommon/foldersettings.h
/usr/include/KF5/mailcommon/foldertreeview.h
/usr/include/KF5/mailcommon/foldertreewidget.h
/usr/include/KF5/mailcommon/foldertreewidgetproxymodel.h
/usr/include/KF5/mailcommon/itemcontext.h
/usr/include/KF5/mailcommon/jobscheduler.h
/usr/include/KF5/mailcommon/kmfilterdialog.h
/usr/include/KF5/mailcommon/mailcommon_export.h
/usr/include/KF5/mailcommon/mailcommonsettings_base.h
/usr/include/KF5/mailcommon/mailfilter.h
/usr/include/KF5/mailcommon/mailinterfaces.h
/usr/include/KF5/mailcommon/mailkernel.h
/usr/include/KF5/mailcommon/mailutil.h
/usr/include/KF5/mailcommon/mdnstateattribute.h
/usr/include/KF5/mailcommon/metatype.h
/usr/include/KF5/mailcommon/pop3settings.h
/usr/include/KF5/mailcommon/redirectdialog.h
/usr/include/KF5/mailcommon/resourcereadconfigfile.h
/usr/include/KF5/mailcommon/searchpattern.h
/usr/include/KF5/mailcommon/searchpatternedit.h
/usr/include/KF5/mailcommon/searchrule.h
/usr/include/KF5/mailcommon/searchrulestatus.h
/usr/include/KF5/mailcommon/sendmdnhandler.h
/usr/include/KF5/mailcommon/snippetsmanager.h
/usr/include/KF5/mailcommon/tag.h
/usr/include/KF5/mailcommon/tagwidget.h
/usr/include/KF5/mailcommon_version.h
/usr/lib64/cmake/KF5MailCommon/KF5MailCommonConfig.cmake
/usr/lib64/cmake/KF5MailCommon/KF5MailCommonConfigVersion.cmake
/usr/lib64/cmake/KF5MailCommon/KF5MailCommonTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5MailCommon/KF5MailCommonTargets.cmake
/usr/lib64/libKF5MailCommon.so
/usr/lib64/qt5/mkspecs/modules/qt_MailCommon.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF5MailCommon.so.5
/usr/lib64/libKF5MailCommon.so.5.9.0
/usr/lib64/qt5/plugins/designer/mailcommonwidgets.so

%files license
%defattr(-,root,root,-)
/usr/share/doc/mailcommon/COPYING
/usr/share/doc/mailcommon/COPYING.LIB

%files locales -f libmailcommon.lang
%defattr(-,root,root,-)

